site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md

theme:
  name: material
  palette:
    primary: cyan
    scheme: slate
    language: es
  features:
    - navigation.tabs.sticky
  logo: img/fva.gif
  extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk

