site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md

theme:
  name: material
  palette:
    primary: cyan
    scheme: slate
    language: es
  features:
    - navigation.tabs.sticky
  logo: img/fva.gif
  copyright: Copyright &copy; 2016 - 2020 Martin Donath

